package souc;

import java.util.*;

public class Array {
	
	public static void main(String[] args) {
       ArrayList <Integer> num=new ArrayList<Integer>();
       //numero esim
       num.add(5);
       num.add(8);
       //num.add(2, 4);
       //num.set(1, 20);
       num.add(1, 4);
       //num.remove(0);
       //System.out.println(num);
       //System.out.println(num.get(0));
       System.out.println(num);
  //  Similarity between Array an ArrayList is the object
      //  difference between Array an ArrayList 
    // 1 Array is a data structure in java
    // ArrayList is an added class in java
  // 2 Array it has a specific size
  //   ArrayList grow and shrink
  // 3 Array can hold  primitive data type or object
  // ArrayList can only hold object
           ///Access Modifier
           //
	}
}