package marksal;

public class Fran {

	public static void main(String[] args) {
        String message="i love u\n"+"Jesus";
        if(message=="i love u") {  
        	 System.err.println(message.toUpperCase());
        }else {
        	  System.err.println(message.toLowerCase());
        }
       
        //System.err.println(message.length());
        // System.out.println(message.indexOf(-1));
	}

}
